/*
 * Generated by the Jasper component of Apache Tomcat
 * Version: Apache Tomcat/8.0.20
 * Generated at: 2016-06-11 02:15:58 UTC
 * Note: The last modified time of this file was set to
 *       the last modified time of the source file after
 *       generation to assist with modification tracking.
 */
package org.apache.jsp.pages.environment;

import javax.servlet.*;
import javax.servlet.http.*;
import javax.servlet.jsp.*;

public final class weathernow_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent,
                 org.apache.jasper.runtime.JspSourceImports {

  private static final javax.servlet.jsp.JspFactory _jspxFactory =
          javax.servlet.jsp.JspFactory.getDefaultFactory();

  private static java.util.Map<java.lang.String,java.lang.Long> _jspx_dependants;

  private static final java.util.Set<java.lang.String> _jspx_imports_packages;

  private static final java.util.Set<java.lang.String> _jspx_imports_classes;

  static {
    _jspx_imports_packages = new java.util.HashSet<>();
    _jspx_imports_packages.add("javax.servlet");
    _jspx_imports_packages.add("javax.servlet.http");
    _jspx_imports_packages.add("javax.servlet.jsp");
    _jspx_imports_classes = null;
  }

  private javax.el.ExpressionFactory _el_expressionfactory;
  private org.apache.tomcat.InstanceManager _jsp_instancemanager;

  public java.util.Map<java.lang.String,java.lang.Long> getDependants() {
    return _jspx_dependants;
  }

  public java.util.Set<java.lang.String> getPackageImports() {
    return _jspx_imports_packages;
  }

  public java.util.Set<java.lang.String> getClassImports() {
    return _jspx_imports_classes;
  }

  public void _jspInit() {
    _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
    _jsp_instancemanager = org.apache.jasper.runtime.InstanceManagerFactory.getInstanceManager(getServletConfig());
  }

  public void _jspDestroy() {
  }

  public void _jspService(final javax.servlet.http.HttpServletRequest request, final javax.servlet.http.HttpServletResponse response)
        throws java.io.IOException, javax.servlet.ServletException {

final java.lang.String _jspx_method = request.getMethod();
if (!"GET".equals(_jspx_method) && !"POST".equals(_jspx_method) && !"HEAD".equals(_jspx_method) && !javax.servlet.DispatcherType.ERROR.equals(request.getDispatcherType())) {
response.sendError(HttpServletResponse.SC_METHOD_NOT_ALLOWED, "JSPs only permit GET POST or HEAD");
return;
}

    final javax.servlet.jsp.PageContext pageContext;
    javax.servlet.http.HttpSession session = null;
    final javax.servlet.ServletContext application;
    final javax.servlet.ServletConfig config;
    javax.servlet.jsp.JspWriter out = null;
    final java.lang.Object page = this;
    javax.servlet.jsp.JspWriter _jspx_out = null;
    javax.servlet.jsp.PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html; charset=UTF-8");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			null, true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;

      out.write("\r\n");
      out.write("<!DOCTYPE HTML>\r\n");
      out.write("<html>\r\n");
      out.write("  <head>\r\n");
      out.write("  <meta http-equiv=\"X-UA-Compatible\" content=\"IE=edge\">\r\n");
      out.write("  <meta content=\"width=device-width, initial-scale=1, maximum-scale=1, user-scalable=no\" name=\"viewport\">\r\n");
      out.write("  <link rel=\"stylesheet\" href=\"../../bootstrap/css/bootstrap.min.css\">\r\n");
      out.write("  <link rel=\"stylesheet\" href=\"https://cdnjs.cloudflare.com/ajax/libs/font-awesome/4.5.0/css/font-awesome.min.css\">\r\n");
      out.write("  <link rel=\"stylesheet\" href=\"https://cdnjs.cloudflare.com/ajax/libs/ionicons/2.0.1/css/ionicons.min.css\">\r\n");
      out.write("  <link rel=\"stylesheet\" href=\"../../dist/css/AdminLTE.min.css\">\r\n");
      out.write("  <link rel=\"stylesheet\" href=\"../../dist/css/skins/skin-blue.min.css\">\r\n");
      out.write("   <title>健康卫士 </title>\r\n");
      out.write("  </head>\r\n");
      out.write("  \r\n");
      out.write(" \r\n");
      out.write("<body class=\"hold-transition skin-blue sidebar-mini\">\r\n");
      out.write("\r\n");
      out.write("<div class=\"wrapper\">\r\n");
      out.write("  ");
      org.apache.jasper.runtime.JspRuntimeLibrary.include(request, response, "../index/header.html", out, true);
      out.write("\r\n");
      out.write("  ");
      org.apache.jasper.runtime.JspRuntimeLibrary.include(request, response, "../index/sidebar.html", out, true);
      out.write("\r\n");
      out.write("\r\n");
      out.write("  <div class=\"content-wrapper\">\r\n");
      out.write("    <!-- Content Header (Page header) -->\r\n");
      out.write("    <section class=\"content-header\">\r\n");
      out.write("      <h1> 健康卫士\r\n");
      out.write("        <small>监控面板</small>\r\n");
      out.write("      </h1>\r\n");
      out.write("      <ol class=\"breadcrumb\">\r\n");
      out.write("        <li><a href=\"#\"><i class=\"fa fa-dashboard\"></i> 健康卫士</a></li>\r\n");
      out.write("        <li class=\"active\">主页</li>\r\n");
      out.write("      </ol>\r\n");
      out.write("    </section>\r\n");
      out.write("    \r\n");
      out.write("     <!-- Main content -->\r\n");
      out.write("\r\n");
      out.write("          <section class=\"content\"> \r\n");
      out.write("      <!-- Small boxes (Stat box) -->\r\n");
      out.write("      \r\n");
      out.write("   \r\n");
      out.write("     \r\n");
      out.write("          <div class=\"row\">\r\n");
      out.write("          <div class=\"col-lg-3\" align=\"right\">     \r\n");
      out.write(" \t\t\t\t <p >请输入查询城市</p>  </div>  \r\n");
      out.write("                  <div class=\"col-lg-1\">     \r\n");
      out.write("                <input type=\"text\" class=\"form-control\" style=\"height: 22px\" >\r\n");
      out.write("                </div>\r\n");
      out.write("                <button style=\"height:22px\">确定</button> \r\n");
      out.write("                \r\n");
      out.write("                \r\n");
      out.write("          </div>\r\n");
      out.write("       \r\n");
      out.write("            <div class=\"col-lg-3 col-xs-6\"> \r\n");
      out.write("              <!-- small box -->\r\n");
      out.write("              <div class=\"small-box bg-aqua\">\r\n");
      out.write("                <div class=\"inner\">\r\n");
      out.write("                  <h3>开封</h3>\r\n");
      out.write("                  <p>当前城市</p>\r\n");
      out.write("                </div>\r\n");
      out.write("            <div class=\"icon\"> <i class=\"ion ion-pie-graph\"></i> </div>\r\n");
      out.write("                <a href=\"#\" class=\"small-box-footer\"><i class=\"fa fa-arrow-circle-right\"></i></a> \r\n");
      out.write("                </div>\r\n");
      out.write("            </div>\r\n");
      out.write("            <!-- ./col -->\r\n");
      out.write("            \r\n");
      out.write("            <div class=\"col-lg-3 col-xs-6\"> \r\n");
      out.write("              <!-- small box -->\r\n");
      out.write("              <div class=\"small-box bg-green\">\r\n");
      out.write("                <div class=\"inner\">\r\n");
      out.write("                  <h3>1993.3.3<sup style=\"font-size: 20px\">*C</sup></h3>\r\n");
      out.write("                  <p>发布时间</p>\r\n");
      out.write("                </div>\r\n");
      out.write("                <div class=\"icon\"> <i class=\"ion ion-stats-bars\"></i> </div>\r\n");
      out.write("                <a href=\"#\" class=\"small-box-footer\"> <i class=\"fa fa-arrow-circle-right\"></i></a> \r\n");
      out.write("                </div>\r\n");
      out.write("          </div> \r\n");
      out.write("       \r\n");
      out.write("            <div class=\"col-lg-3 col-xs-6\"> \r\n");
      out.write("              <!-- small box -->\r\n");
      out.write("              <div class=\"small-box bg-yellow\">\r\n");
      out.write("                <div class=\"inner\">\r\n");
      out.write("                  <h3>二</h3>\r\n");
      out.write("                   <p>星期</p>\r\n");
      out.write("                </div>\r\n");
      out.write("               <div class=\"icon\"> <i class=\"ion ion-pie-graph\"></i> </div>\r\n");
      out.write("                <a href=\"#\" class=\"small-box-footer\"><i class=\"fa fa-arrow-circle-right\"></i></a> \r\n");
      out.write("                </div>\r\n");
      out.write("            </div>\r\n");
      out.write("            <!-- ./col -->\r\n");
      out.write("            <div class=\"col-lg-3 col-xs-6\"> \r\n");
      out.write("              <!-- small box -->\r\n");
      out.write("              <div class=\"small-box bg-red\">\r\n");
      out.write("                <div class=\"inner\">\r\n");
      out.write("                  <h3>晴</h3>\r\n");
      out.write("                  <p>天气</p>\r\n");
      out.write("                </div>\r\n");
      out.write("                 <div class=\"icon\"> <i class=\"ion ion-stats-bars\"></i> </div>\r\n");
      out.write("                <a href=\"#\" class=\"small-box-footer\"><i class=\"fa fa-arrow-circle-right\"></i></a>\r\n");
      out.write("                 </div>\r\n");
      out.write("            </div>\r\n");
      out.write("            \r\n");
      out.write("                    <div class=\"col-lg-3 col-xs-6\"> \r\n");
      out.write("              <!-- small box -->\r\n");
      out.write("              <div class=\"small-box bg-aqua\">\r\n");
      out.write("                <div class=\"inner\">\r\n");
      out.write("                  <h3>5*C</h3>\r\n");
      out.write("                  <p>气温</p>\r\n");
      out.write("                </div>\r\n");
      out.write("               <div class=\"icon\"> <i class=\"ion ion-pie-graph\"></i> </div>\r\n");
      out.write("                <a href=\"#\" class=\"small-box-footer\"><i class=\"fa fa-arrow-circle-right\"></i></a>\r\n");
      out.write("                 </div>\r\n");
      out.write("            </div>\r\n");
      out.write("            \r\n");
      out.write("                   <div class=\"col-lg-3 col-xs-6\"> \r\n");
      out.write("              <!-- small box -->\r\n");
      out.write("              <div class=\"small-box bg-green\">\r\n");
      out.write("                <div class=\"inner\">\r\n");
      out.write("                  <h3>5*C</h3>\r\n");
      out.write("                  <p>体感温度</p>\r\n");
      out.write("                </div>\r\n");
      out.write("                   <div class=\"icon\"> <i class=\"ion ion-stats-bars\"></i> </div>\r\n");
      out.write("                <a href=\"#\" class=\"small-box-footer\"><i class=\"fa fa-arrow-circle-right\"></i></a>\r\n");
      out.write("                 </div>\r\n");
      out.write("            </div>\r\n");
      out.write("                \r\n");
      out.write("             <div class=\"col-lg-3 col-xs-6\"> \r\n");
      out.write("              <!-- small box -->\r\n");
      out.write("              <div class=\"small-box bg-yellow\">\r\n");
      out.write("                <div class=\"inner\">\r\n");
      out.write("                  <h3>53mm</h3>\r\n");
      out.write("                  <p>降雨量</p>\r\n");
      out.write("                </div>\r\n");
      out.write("               <div class=\"icon\"> <i class=\"ion ion-pie-graph\"></i> </div>\r\n");
      out.write("                <a href=\"#\" class=\"small-box-footer\"><i class=\"fa fa-arrow-circle-right\"></i></a>\r\n");
      out.write("                 </div>\r\n");
      out.write("            </div>       <div class=\"col-lg-3 col-xs-6\"> \r\n");
      out.write("              <!-- small box -->\r\n");
      out.write("              <div class=\"small-box bg-red\">\r\n");
      out.write("                <div class=\"inner\">\r\n");
      out.write("                  <h3>33%</h3>\r\n");
      out.write("                  <p>湿度</p>\r\n");
      out.write("                </div>\r\n");
      out.write("                 <div class=\"icon\"> <i class=\"ion ion-stats-bars\"></i> </div>\r\n");
      out.write("                <a href=\"#\" class=\"small-box-footer\"><i class=\"fa fa-arrow-circle-right\"></i></a>\r\n");
      out.write("                 </div>\r\n");
      out.write("            </div>\r\n");
      out.write("            \r\n");
      out.write("             <div class=\"col-lg-3 col-xs-6\"> \r\n");
      out.write("              <!-- small box -->\r\n");
      out.write("              <div class=\"small-box bg-aqua\">\r\n");
      out.write("                <div class=\"inner\">\r\n");
      out.write("                  <h3>1014</h3>\r\n");
      out.write("                  <p> 大气压</p>\r\n");
      out.write("                </div>\r\n");
      out.write("              <div class=\"icon\"> <i class=\"ion ion-pie-graph\"></i> </div>\r\n");
      out.write("                <a href=\"#\" class=\"small-box-footer\"><i class=\"fa fa-arrow-circle-right\"></i></a>\r\n");
      out.write("                 </div>\r\n");
      out.write("            </div>      \r\n");
      out.write("            \r\n");
      out.write("             <div class=\"col-lg-3 col-xs-6\"> \r\n");
      out.write("              <!-- small box -->\r\n");
      out.write("              <div class=\"small-box bg-green\">\r\n");
      out.write("                <div class=\"inner\">\r\n");
      out.write("                  <h3>西南风</h3>\r\n");
      out.write("                  <p> 风向</p>\r\n");
      out.write("                </div>\r\n");
      out.write("                  <div class=\"icon\"> <i class=\"ion ion-stats-bars\"></i> </div>\r\n");
      out.write("                <a href=\"#\" class=\"small-box-footer\"><i class=\"fa fa-arrow-circle-right\"></i></a>\r\n");
      out.write("                 </div>\r\n");
      out.write("            </div>\r\n");
      out.write("                  \r\n");
      out.write("             <div class=\"col-lg-3 col-xs-6\"> \r\n");
      out.write("              <!-- small box -->\r\n");
      out.write("              <div class=\"small-box bg-yellow\">\r\n");
      out.write("                <div class=\"inner\">\r\n");
      out.write("                  <h3>微风</h3>\r\n");
      out.write("                  <p>  风力</p>\r\n");
      out.write("                </div>\r\n");
      out.write("               <div class=\"icon\"> <i class=\"ion ion-pie-graph\"></i> </div>\r\n");
      out.write("                <a href=\"#\" class=\"small-box-footer\"><i class=\"fa fa-arrow-circle-right\"></i></a>\r\n");
      out.write("                 </div>\r\n");
      out.write("            </div>       \r\n");
      out.write("            \r\n");
      out.write("            <div class=\"col-lg-3 col-xs-6\"> \r\n");
      out.write("              <!-- small box -->\r\n");
      out.write("              <div class=\"small-box bg-red\">\r\n");
      out.write("                <div class=\"inner\">\r\n");
      out.write("                  <h3>3.2m/s</h3>\r\n");
      out.write("                  <p> 风速</p>\r\n");
      out.write("                </div>\r\n");
      out.write("                <div class=\"icon\"> <i class=\"ion ion-stats-bars\"></i> </div>\r\n");
      out.write("                <a href=\"#\" class=\"small-box-footer\"><i class=\"fa fa-arrow-circle-right\"></i></a>\r\n");
      out.write("                 </div>\r\n");
      out.write("            </div>\r\n");
      out.write("    \r\n");
      out.write("           \r\n");
      out.write("\r\n");
      out.write("        <!--    <section class=\"col-lg-3 connectedSortable\"> </section> --> \r\n");
      out.write("        \r\n");
      out.write("   \r\n");
      out.write("      \r\n");
      out.write("      <!-- Main row --> \r\n");
      out.write("      \r\n");
      out.write("    </section>\r\n");
      out.write("    \r\n");
      out.write("\r\n");
      out.write("    </div>\r\n");
      out.write("  <!-- /.content-wrapper -->\r\n");
      out.write(" ");
      org.apache.jasper.runtime.JspRuntimeLibrary.include(request, response, "../index/footer.html", out, true);
      out.write("\r\n");
      out.write("</div>\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("<!-- jQuery 2.2.0 -->\r\n");
      out.write("<script src=\"../../plugins/jQuery/jQuery-2.2.0.min.js\"></script>\r\n");
      out.write("<!-- Bootstrap 3.3.6 -->\r\n");
      out.write("<script src=\"../../bootstrap/js/bootstrap.min.js\"></script>\r\n");
      out.write("<!-- AdminLTE App -->\r\n");
      out.write("<script src=\"../../dist/js/app.min.js\"></script>\r\n");
      out.write("</body>\r\n");
      out.write("</html>\r\n");
    } catch (java.lang.Throwable t) {
      if (!(t instanceof javax.servlet.jsp.SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try {
            if (response.isCommitted()) {
              out.flush();
            } else {
              out.clearBuffer();
            }
          } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
        else throw new ServletException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }
}
